letscoding:
  datasource:
    postgress:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgress
      driverClassName: org.postgresql.Driver
      server-name: localhost
      port-number: 8052
      database-name: postgress