letscoding:
  datasource:
    postgress:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: benimSifrem
      driverClassName: org.postgresql.Driver
      server-name: localhost
      port-number: 5432
      database-name: postgres